ConsoleUpdateV1.2
macroquest/macroquest pull request #590
Opened 2022-07-29 01:58 UTC by Atomfusion1

This Update is for the Console window, Adding additional functionality 
1. Added Settings under Windows-> Console
      A. Lock Window 
      B. Hide TitleBar 
      C. Window Alpha Normal 
      D. Window Alpha Fade 
      E. Console Font Size Adjustment 
      F. UI Selector under console (Can Select Fonts for all Windows and Console text 

Files Changed ImGuiUtils: 
1. Added 2 Additional Font Sizes of Lucon 15 and 17 

MQ2ImGuiConsole:
GetConsolesFlags() Function to handle Flags 
MouseOverUpdate() Function to handle Window Fade Delay from Normal to Fade Condition 
Set m_zepEditor to use Global Font with Selectable Size 
FontNumberFromString() Get Front[#] from Debug String file name 
Created ImGui Items for Console Window, 2 check boxes 3 sliders 1 font control 
Save All Changes to MacroQuest.ini 
Changed Save Location from [Macroquest] to [MQConsole] As now there are 7+ options 
Saving: ConsoleFontOnStartup, ShowMacroQuestConsole, LockConsoleWindow, NoTitlebar, ConsoleFontSize, AlphaFadeOnStartup, AlphaNormalOnStartup
Autoload all options on Startup 
Set Default Values for All Options if Button Pressed

2022-07-29 08:03 UTC, brainiac requested changes
we have a bit of an issue here in that the whole file has been reformatted. Please pay attention to the changes in your commits before you make them. I can't review this in its current state. Please revert the formatting changes.

2022-07-29 08:14 UTC, brainiac commented on src/main/MQ2ImGuiConsole.cpp
> +				s_isMouseInFadeDelay = true;
why is this a static variable but the one above it is a member variable?

2022-07-29 08:14 UTC, brainiac commented on src/main/MQ2ImGuiConsole.cpp
> +		ImGuiWindowFlags GetConsolesFlags()
this doesn't really need to be a function, but theres a typo in its name anyhow.

2022-07-29 08:15 UTC, brainiac commented on src/main/MQ2ImGuiConsole.cpp
> +				if (std::chrono::duration_cast<std::chrono::seconds>(std::chrono::steady_clock::now() - m_pr_StartTime ) < std::chrono::seconds(s_mouseHoverTimerSecondsDelay))
s_mouseHoverTimerSecondsDelay should be stored as a std::chrono::seconds, not a uint16_t. then you wouldn't need all these casts.

2022-07-29 08:16 UTC, brainiac commented on src/main/MQ2ImGuiConsole.cpp
> +				}
this is basically `if (a) { return true } else { return false }
just assign the variable to the result of the conditio.

2022-07-29 08:51 UTC, brainiac commented on src/main/MQ2ImGuiConsole.cpp
> +			WritePrivateProfileBool("MQConsole", "ShowMacroQuestConsole", s_consoleVisibleOnStartup, mq::internal_paths::MQini);
you shouldn't change the names of existin gsettings.

2022-07-29 08:52 UTC, brainiac commented on src/main/MQ2ImGuiConsole.cpp
> +			if (strcmp(fontstr.c_str(), fontString.c_str()) == 0)
you took a const char*, turned it into a std::string, and then took the const char* back out.

This function can take a string_view and use ci_equals from the mq string library.

function name isn't correct. "FontNumberFromString" - what about the font number? what are we doing with it? Getting it? converting it? etc

2022-07-29 08:53 UTC, brainiac commented on src/main/MQ2ImGuiConsole.cpp
> +		mq::imgui::HelpMarker("This feature allows you to automatically lock the MacroQuest Console.");
this doesn't tell me what locking the console means.

2022-07-29 08:54 UTC, brainiac commented on src/main/MQ2ImGuiConsole.cpp
> +		mq::imgui::HelpMarker("This feature allows you to hide MacroQuest Menu Bar.");
+the, Menu Bar should be lower cased. Should probably make some mention of the title bar since the option is called "Hide Titlebar"

2022-07-29 08:55 UTC, brainiac commented on src/main/MQ2ImGuiConsole.cpp
> +		ImGui::Text("Alpha Normal");
These options need some explanation as i'm not sure what i'm looking at based on their names.

Also, these sliders have labels on the right side, might want to use the space that is reserved for the labels or else remove the extra spacing.

2022-07-29 08:56 UTC, brainiac commented on src/main/MQ2ImGuiConsole.cpp
> +			ImGui::GetIO().FontDefault = ImGui::GetIO().Fonts->Fonts[fontNumber];
the console font is not the default font.

2022-07-29 08:57 UTC, brainiac commented on src/main/MQ2ImGuiConsole.cpp
> +			ImGui::SetNextWindowBgAlpha(s_isMouseInFadeDelay ? s_alphaConsoleNormal * .01f : s_alphaConsoleFade * .01f);
factor out the math from this condition

2022-07-29 08:59 UTC, brainiac commented on src/main/MQ2ImGuiConsole.cpp
> +		std::chrono::steady_clock::time_point m_pr_StartTime;
what is the "pr" signifying?

2022-07-29 09:00 UTC, brainiac commented on src/main/MQ2ImGuiConsole.cpp
> +		void MouseOverUpdate()
this function does something with side effects, it should be named like a verb.

2022-07-29 09:01 UTC, brainiac commented on src/main/MQ2ImGuiConsole.cpp
> +			m_zepEditor->mq::imgui::ImGuiZepEditor::SetFont(Zep::ZepTextType::Text, ImGui::GetFont(), s_consoleFontSize);
SetFont should only be called if the font is being changed.

`m_zepEditor->SetFont`, the whole function scope doesn't need to be qualified.

2022-07-29 09:03 UTC, brainiac commented on src/main/MQ2ImGuiConsole.cpp
> +		s_consoleFontName = GetPrivateProfileString("MQConsole", "ConsoleFontOnStartup", "Lucon.ttf, 13px", mq::internal_paths::MQini);
the default here is capitalized, but FontNumberFromString is using a case sensitive comparison.

2022-07-29 09:04 UTC, brainiac commented on src/main/MQ2ImGuiConsole.cpp
> +			s_consoleFontSize = 13;
this is set twice.

2022-07-29 09:07 UTC, brainiac commented on src/main/MQ2ImGuiConsole.cpp
> +		if (fontstr != consoleDebugName)
use ci_equals so you don't have to copy these into std::strings

2022-07-29 09:09 UTC, brainiac commented on src/main/MQ2ImGuiConsole.cpp
> +			ImGui::GetIO().FontDefault = ImGui::GetIO().Fonts->Fonts[fontNumber];
you should detect if the font is not found and fall back to the default console font (mq::imgui::ConsoleFont)

2022-07-30 03:56 UTC, Atomfusion1 commented
I messed this Pull Request up, All changes have been made and are now in ConsoleUpdateV1.3 Thanks for your Advice

2022-07-30 03:56 UTC, closed without merging