Master add sol imgui bindings
macroquest/macroquest pull request #658
Opened 2022-11-11 15:27 UTC by projecteon

Added bindings for table column flag checks.
The sample code for context menu in table columns use these.

2022-11-11 17:24 UTC, brainiac commented on src/plugins/lua/contrib/imgui/sol_ImGui.h
> +	inline bool TableGetColumnHasFlag(int column_n, ImGuiTableColumnFlags flag)							{ return (ImGui::TableGetColumnFlags(column_n) & flag) != 0; }
please use spaces instead of tabs for aligning the function bodies

2022-11-11 17:25 UTC, brainiac requested changes
please use spaces instead of tabs for aligning the function bodies

2022-11-12 14:22 UTC, projecteon commented
Updated, 
Sorry, Im used to having tools (ie editorconfig) that does this automatically for me.

2022-11-16 06:44 UTC, brainiac commented
turn on whitespace markers so you can see :)

We do have editor config, the indentation should be tabs, but the alignment for the function bodies is spaces. indentation and alignment are two different things here.

I'll fix.t

2022-11-16 06:44 UTC, merged