add option to not clean links from mq.events
macroquest/macroquest pull request #891
Opened 2024-08-12 10:30 UTC by grimmier378

if unchecked mq.events will not strip links from the line.

This way we preserve the item links from chat when printing the line back.

https://github.com/user-attachments/assets/0bf77243-08f5-4718-a7d1-701bd86aa9eb

2024-08-12 16:58 UTC, brainiac requested changes
This fails to account for some critical details:
- By being a user setting, this assumes that the user knows the correct setting to be used to be compatible with a running script
- It preclues the ability to run two scripts, or even events, simultaneously, where one requires stripping of chat links, and the other does not.

Note that stripping of chat links in events isn't a user preference. This is something that the event itself would need to opt into.

2024-08-12 20:07 UTC, grimmier378 commented
I see your point and also agree. 

maybe making it so `mq.events(name, pattern, callback, showlink) ` where showlink is optional and defaults to false which is the current way it works, where they are always stripped?

2024-08-12 20:50 UTC, brainiac commented
I'd probably go one step further and make it be `mq.events(name, pattern, callback, options)` where options is a table.

you would call it like `mq.events(name, pattern, callback, {keep_links = True})` or something

2024-08-13 14:00 UTC, grimmier378 commented
https://vimeo.com/998196547/ef502773a4?share=copy

test script used
[test_events.lua.txt](https://github.com/user-attachments/files/16600634/test_events.lua.txt)

2024-08-13 17:25 UTC, brainiac commented on src/plugins/lua/LuaEvent.cpp
> +	, m_keep_links(false)
`m_keepLinks`, this should be initialized in the header

2024-08-13 17:25 UTC, brainiac commented on src/plugins/lua/LuaEvent.cpp
> +	const sol::table& options, // Accept options table
redundant comment provides no value.

2024-08-13 17:29 UTC, brainiac commented on src/plugins/lua/MQ2Lua.cpp
> +
You need to remove all this code from the first implementation still.

2024-08-13 17:29 UTC, brainiac commented on src/plugins/lua/LuaEvent.h
> +	bool m_keep_links; // Store the keep_links option
Did you use AI to write all this?

2024-08-13 17:32 UTC, brainiac commented on src/plugins/lua/LuaEvent.cpp
> +	}
If you pass in the optional table as I described in another comment, you can do something like this. The valid checks are redundant in this case.

```
if (options.has_value())
{
    m_keepLinks = options["keep_links"].get_or_(false);
}
```

2024-08-13 17:33 UTC, brainiac commented on src/plugins/lua/LuaEvent.h
> +	std::string_view GetExpression() const { return m_expression; } // Add accessor for expression
???

2024-08-13 17:33 UTC, brainiac commented on src/plugins/lua/LuaEvent.cpp
> +		return;
We shouldn't get this far if the line has no value.

2024-08-14 02:39 UTC, grimmier378 commented on src/plugins/lua/LuaEvent.cpp
> +	}
I do ask copilot for help when I hit a wall, and there were a few in this one.
It loves to over comment to explain stuff to me.

2024-09-02 22:14 UTC, brainiac commented
Will pull some of this into some other link-related work that I am doing.

2024-09-02 22:14 UTC, closed without merging

2024-09-02 22:36 UTC, grimmier378 commented
> Will pull some of this into some other link-related work that I am doing.

copy that, on a plus note it has been working well for me in testing these last few weeks..